--Table structure for table `parts`
CREATE TABLE public.parts (
    part_id INT GENERATED BY DEFAULT AS IDENTITY,
    part_name CHARACTER VARYING NOT NULL,
    part_description text NOT NULL,
    part_image character varying NOT NULL,
    part_thumbnail character varying NOT NULL,
    part_price numeric (9, 0) NOT NULL,
    CONSTRAINT parts_pk PRIMARY KEY (part_id)
);
-- Data for table `parts`
INSERT INTO public.parts (
        part_name,
        part_description,
        part_image,
        part_thumbnail,
        part_price
    )
VALUES (
        'Flux Capacitor',
        'Going to the future? You will not get there (or then) without one of these babies!',
        './images/parts/flux-cap.jpg',
        './images/parts/flux-cap-tn.jpg',
        2500
    ),
    (
        'Muffler Bearings',
        'Car too loud for you? Let us help you with some new muffler bearings. These could make all the difference.',
        './images/parts/muffler-bearing.jpg',
        './images/parts/muffler-bearing-tn.jpg',
        500
    ),
    (
        'Headlight Fluid',
        'Your lights will never be brighter than if you keep your headlight fluid fresh!',
        './images/parts/headlight-fluid.jpg',
        './images/parts/headlight-fluid-tn.jpg',
        150
    ),
    (
        'Blinker Fluid',
        'Are your blinker signals slowing down, speeding up, or just not working? Blinker Fluid could be the answer to the problem.',
        './images/parts/blinker-fluid.jpg',
        './images/parts/blinker-fluid-tn.jpg',
        100
    ),
    (
        'Round Tuit',
        'Sometimes you just need to get a... this.',
        './images/parts/round-tuit.jpg',
        './images/parts/round-tuit-tn.jpg',
        2000
    ),
    (
        'Passing Gear Fluid',
        'If your car struggles to get past some of the quicker cars on the road these days, this is for you.',
        './images/parts/passing-gear-fluid.jpg',
        './images/parts/passing-gear-fluid-tn.jpg',
        120
    ),
    (
        'No-Touch Wiper Blades',
        'You will never have an easier time in any rain storm.',
        '/images/parts/no-image.png',
        './images/parts/no-image-tn.png',
        20
    ),
    (
        'Flame Decals',
        'Nothing can make your car look more amazing than FLAMES!',
        '/images/parts/flame.jpg',
        '/images/parts/flame.jpg',
        55
    ),
    (
        'Bumper Stickers',
        'Impress your friends with your coding knowledge by showing off the first assignment anyone ever completes- Hello World.',
        '/images/parts/bumper_sticker.jpg',
        '/images/parts/bumper_sticker.jpg',
        15
    ),
    (
        'Hub Caps',
        'Cover up ugly wheels with these fantastic fixtures!',
        '/images/parts/hub-cap.jpg',
        '/images/parts/hub-cap.jpg',
        150
    );